# Generated by Django 2.0.1 on 2018-01-23 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_FirstName', models.CharField(blank=True, max_length=20, null=True, verbose_name='FirstName')),
                ('Account_Name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Name')),
                ('Account_LastName', models.CharField(blank=True, max_length=30, null=True, verbose_name='LastName')),
                ('Account_NickName', models.CharField(max_length=20, verbose_name='Nickname')),
                ('Account_Birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('Account_RegistretedAt', models.DateTimeField(auto_now_add=True, verbose_name='RegistreteAt')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_LikesAccount', to='TwitterProject.Account', verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Title', models.CharField(max_length=50, verbose_name='Caption')),
                ('Post_Context', models.TextField(verbose_name='Context')),
                ('Post_CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='DatePub')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_PostAccount', to='TwitterProject.Account', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag_Name', models.CharField(blank=True, max_length=30, null=True, verbose_name='TagName')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='TagCollection',
            field=models.ManyToManyField(related_name='r_PostsTag', to='TwitterProject.Tag', verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='likes',
            name='PostLink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_PostLikes', to='TwitterProject.Post', verbose_name='Post'),
        ),
    ]
